#
# $Source: f:/miner/source/includes/rcs/makefile $
# $Revision: 1.1 $
# $Author: matt $
# $Date: 1993/11/04 10:24:14 $
#
# Makefile for macro and header files
#

LIBDIR = ..\main

# What compiler and flags to use
CC = wcc386
CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG /zq

# What assembler and flags to use
ASM = ml
ASMFLAGS = /c /nologo

# What to install
INSTALL_TARGS = types.h types.inc psmacros.inc

# What to clean
CLEAN_TARGS = *.obj *.lib *.err

